#!/bin/sh
set -e

cd "$AUTOPKGTEST_TMP"
git init -b dominus
echo meow >meow
export GIT_AUTHOR_NAME='Julius Caesar'
export GIT_AUTHOR_EMAIL='imperator@spqr.it'
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
git add meow
git commit -m Meow!
git brute -prefix beef
git log|head -n1|grep -q '^commit beef'
